# Generated by Django 4.0.4 on 2022-05-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Shoe Status Date')),
                ('status', models.CharField(choices=[('O', 'Own Shoe'), ('D', "Don't Own"), ('P', 'Plan to Own')], default='O', max_length=1)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shoe')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
